### ISSUE TITLE
Make it work for browserify

### ISSUE THREAD

**Issue by ptarjan** [niftylettuce/email-templates#143]
Can you get your module to work with https://github.com/substack/node-browserify please? I use it on my server to bundle all the modules together for deployment (since I'm on Parse's Cloud code).

The one major change would probably be instead of passing a template dir to the constructor, to pass an object with the already read-in templates (and maybe their filenames so you can know what engine to use). https://github.com/substack/brfs can handle `fs.readFileSync` but it can't trace through all the dynamic code to package together the include.

Now to trying to get it to run. If you make a simple script:

```
var path = require('path');
var EmailTemplate = require('email-templates').EmailTemplate;
var templateDir = path.join(__dirname, 'templates', 'foo');
var template = new EmailTemplate(templateDir);
template.render({}).then(function(html) {
  console.log(html);
});
```

it works great, but when run with browserify:

```
$ browserify test.js | node
Error: Cannot find module 'emblem' from 'node_modules/email-templates/lib'
```

Fine, you have a billion optional deps. I'll fight through those and then try:

```
 browserify -u emblem -u less -u stylus -u styl -u tinyliquid -u jade -u then-jade -u dust -u dustjs-helpers -u dustjs-linkedin -u atpl -u swig -u ejs -u liquor -u eco -u jazz -u jqtpl -u hamljs -u hamlet -u whiskers -u haml-coffee -u hogan.js -u templayed -u underscore -u qejs -u mustache -u walrus -u just -u ect -u mote -u toffee -u reactive -u dot -u nunjucks -u ractive -u htmling -u react-tools -u react test.js | node
[stdin]:6443
  if (!require.extensions['.jsx']) {
                         ^
TypeError: Cannot read property '.jsx' of undefined
```

Ok, I guess I'll try patching it by putting a big `if (require.extensions)` around that code. https://github.com/tj/consolidate.js/pull/208 . Try again:

```
[stdin]:3922
        throw new TypeError("fn must be a function\u000a\u000a    See http://g
              ^
TypeError: fn must be a function

    See http://goo.gl/916lJJ

    at Function.Promise.promisify ([stdin]:3922:15)
    at Object../template-manager ([stdin]:414:39)
    at s ([stdin]:1:254)
    at [stdin]:1:305
    at Object../email-template ([stdin]:194:13)
    at s ([stdin]:1:254)
    at [stdin]:1:305
    at Object.<anonymous> ([stdin]:78853:21)
    at Object.email-templates ([stdin]:78863:4)
    at s ([stdin]:1:254)
    at e ([stdin]:1:425)
    at [stdin]:1:443
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
```

Now I'm stuck. I don't see `promisify` in `template-manager`. Can you help getting this working?

**Comment by eahefnawy** [comment]
+1

**Comment by ajagnanan** [comment]
+1

**Comment by manukbenjamin** [comment]
+1

**Comment by niftylettuce** [comment]
try using v3.x?
