### ISSUE TITLE
Error: Cannot find module 'juice'

### ISSUE THREAD

**Issue by ivanakimov** [niftylettuce/email-templates#248]
`email-templates@3.0.8`
`node@8.6.0`
`npm@5.3.0`

```bash
module.js:529
    throw err;
    ^

Error: Cannot find module 'juice'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/juice-resources-promise/index.js:1:77)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/email-templates/index.js:18:24)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/services/sendgrid/index.js:3:15)
    at Module._compile (module.js:624:30)
```

**Comment by niftylettuce** [comment]
@ivanakimov I am not able to reproduce this.  Can you please try `rm -rf node_modules` and `npm install` (or `yarn install`) again?  Or you could specifically completely remove the package and reinstall it.

**Comment by ivanakimov** [comment]
I did try that before posting, but still had the same issue. I'll close it for now if nobody else is experiencing this. We're using `email-templates@3.0.5` right now which works. Thank you for checking it out.

**Comment by niftylettuce** [comment]
3.0.8 should be fine @ivanakimov - can you please test that version again?  how are you testing?

**Comment by ivanakimov** [comment]
`npm install` worked fine this time. I am sure it was something local on my end.

But the `email-templates` API changed so much from v2 to v3 (especially since we were mostly interested in rendering templates) that we ended up switching away from it and writing our own. Thanks for the good support tho.
