### ISSUE TITLE
Getting invalid token issue with lates version

### ISSUE THREAD

**Issue by nasif** [niftylettuce/email-templates#256]
My node version is 
=======================================
G:\brentals\source\Web>node --version
v6.11.3
========================================
When i am starting the node, it is failing becuase of unexpected token in the 'email-tamplates'
Please see the logs.

**G:\brentals\source\Web\node_modules\email-templates\index.js:98
    return new Promise(async (resolve, reject) => {
                             ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\brentals\source\Web\email.js:3:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)**
Once resolved please let me know..

Thanks

**Comment by niftylettuce** [comment]
Please upgrade to latest version, `npm install email-templates@latest`.  We just added legacy node version support

**Comment by niftylettuce** [comment]
@nasif please let me know if that resolves your issue.

**Comment by niftylettuce** [comment]
sent you an email, if any more issues comment here or reply to my email, thanks
