### ISSUE TITLE
Since 5.0.1: Error: Cannot find module ‘juice’

### ISSUE THREAD

**Issue by ibc** [niftylettuce/email-templates#331]
```
Error: Cannot find module ‘juice’
   at Function.Module._resolveFilename (module.js:547:15)
   at Function.Module._load (module.js:474:25)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous> (/service/node_modules/juice-resources-promise/index.js:1:77)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
   at tryModuleLoad (module.js:505:12)
   at Function.Module._load (module.js:497:3)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous> (/service/node_modules/email-templates/lib/index.js:39:24)
   at Module._compile (module.js:652:30)
   at Object.Module._extensions..js (module.js:663:10)
   at Module.load (module.js:565:32)
``` 

My app dependencies:

```json
"dependencies": {
    "ejs": "^2.6.1",
    "email-templates": "^5.0.1",
    "nodemailer": "^4.6.8"
  },
```

**Comment by ibc** [comment]
Interesting:

* `email-templates` dependencies:

```json
"dependencies": {
    "juice": "^5.0.0",
    "juice-resources-promise": "^0.0.2",
}

* `juice-resources-promise` devDependencies:

```json
"devDependencies": {
  "juice": "^4.1.1"
}
```

It seems to me that this is making NPM crazy (just wondering).

**Comment by ibc** [comment]
In fact, the "Cannot find module ‘juice’" does not happen if I install my app dependencies with `npm install`, but it **DOES** happen if I do `npm install --production`.

**Comment by ibc** [comment]
Confirmed that this is a fuxxxxxing bug in NPM, and just happens if `npm i --production` is called and the main add does have `juice 4.xx'  within its `devDependencies`. A complete no-sense.

**Comment by niftylettuce** [comment]
`email-templates@5.0.2` has been released to npm
